# Site settings
title: Codana.me
extra_title: " | home of audio dev michael chadwick"
email: first-name@domain
description: "code and audio (and audio code) developments by <a href='https://michaelchadwick.info'>michael chadwick</a>"
url: "https://codana.me"
baseurl: ""
plugins: [jekyll-paginate]
paginate: 10
encoding: UTF-8
include: ["mus.html", "net.html", "index_print.html"]
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
tag_page_layout: tag_page
tag_page_dir: tags

# Build settings
markdown: kramdown
permalink: pretty

# Custom Site settings
my_name: Michael Chadwick
gh_username: michaelchadwick
tw_username: mjchadwick
sc_username: nebyoolae
bc_username: nebyoolae
gh_link: https://github.com/michaelchadwick
tw_link: https://twitter.com/mjchadwick
sc_link: https://soundcloud.com/nebyoolae
bc_neb_link: https://nebyoolae.bandcamp.com
bc_flv_link: https://flylikevenus.bandcamp.com
bc_mcj_link: https://mcj.nebyoolae.com
bc_pyc_link: https://pureyellow.bandcamp.com
