# Site settings
title: Codana.me
extra_title: " | home of audio dev michael chadwick"
email: first name@domain
description: "code and audio (and audio code) developments by michael chadwick"
url: "http://codana.me"
baseurl: ""
paginate: 10
encoding: UTF-8
include: ["mus.html", "net.html", "index_print.html"]

# Build settings
markdown: kramdown
permalink: pretty

# Custom Site settings
gh_username: michaelchadwick
tw_username: mjchadwick
sc_username: nebyoolae
bc_username: nebyoolae
gh_link: https://github.com/michaelchadwick
tw_link: https://twitter.com/mjchadwick
sc_link: http://soundcloud.com/nebyoolae
bc_link: https://nebyoolae.bandcamp.com
